- entity-client/pom.xml
- entity-common/pom.xml
- entity-mongo/pom.xml
- entity-solr/pom.xml
- entity-web/pom.xml
- entity-web/src/main/java/eu/europeana/entity/web/jsonld/SuggestionSetSerializer.java
- entity-web/src/main/resources/entity-web-mvc.xml
- pom.xml
Change-Id: I56b1b90bd5c30515a403305739a35a72cfb1bb3f
> #20 updated annotation-ld version, enabled cors support

- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/RankedEntity.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/ResolveController.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/SearchController.java
- entity-web/src/main/resources/entity-web-mvc.xml
updated cors configs
Change-Id: I60085c5b9d12ecd531f19a9c4a52c81599134abb
> #60 updated cors configurations. Split configurations for individual

- entity-web/src/main/java/eu/europeana/api/common/config/I18nConstants.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/BaseRest.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/ResolveController.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/SearchController.java
- entity-web/src/main/resources/messages_en.properties
- entity-web/src/main/resources/messages_en.properties.template
Change-Id: I5092be5e75f63d3ff83dbf889f7f4ab44a12ba90
> #62 missing wsKey param returns now 401 error

- pom.xml
Change-Id: I4ed76f6f698d9eea0749f7f06560b5ce542a49a7
> #64 updated commons api version and entity api version

- pom.xml
Change-Id: I2dfaa8d18e6411135e5ef9f9a1702b825102ff7c
> #91 updated dependencies to release versions

- entity-solr/src/main/java/eu/europeana/entity/solr/service/impl/SuggestionUtils.java
Bugfix for language logic
Change-Id: I5d28b29bf56916b0f0c5d7bef77eb92cdc140ede
> #93 EA-1368 changed prefLanguages to mutable list. 

- pom.xml
Change-Id: I09dcbeaa9218115016a667cab6e6bf15be3d5996
> #91 updated version to release

- entity-definitions/src/main/java/eu/europeana/entity/definitions/exceptions/UnsupportedAlgorithmTypeException.java
- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/vocabulary/SearchAlgorithmTypes.java
- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/vocabulary/SuggestAlgorithmTypes.java
- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/vocabulary/WebEntityConstants.java
- entity-solr/src/main/java/eu/europeana/entity/solr/model/vocabulary/SuggestionFields.java
- entity-solr/src/main/java/eu/europeana/entity/solr/service/SolrEntityService.java
- entity-solr/src/main/java/eu/europeana/entity/solr/service/impl/EntityQueryBuilder.java
- entity-solr/src/main/java/eu/europeana/entity/solr/service/impl/SolrEntityServiceImpl.java
- entity-solr/src/main/resources/entity-solr-context.xml
- entity-solr/src/test/java/eu/europeana/entity/solr/service/SolrEntityServiceTest.java
- entity-web/src/main/java/eu/europeana/api/common/config/I18nConstants.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/BaseRest.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/SearchController.java
- entity-web/src/main/java/eu/europeana/entity/web/exception/ParamValidationException.java
- entity-web/src/main/java/eu/europeana/entity/web/service/EntityService.java
- entity-web/src/main/java/eu/europeana/entity/web/service/impl/EntityServiceImpl.java
- entity-web/src/main/resources/messages_en.properties
- pom.xml
suggestion using search handler on label field.
> #89 EA-1337 Created branch and extended RESTful API method for

- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/ConceptScheme.java
- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/impl/BaseConceptScheme.java
- entity-mongo/src/main/java/eu/europeana/grouping/mongo/model/internal/PersistentConceptScheme.java
- entity-solr/src/main/java/eu/europeana/entity/solr/model/SolrConceptScheme.java
- entity-solr/src/main/java/eu/europeana/entity/solr/model/SolrConceptSchemeImpl.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/ConceptSchemeController.java
- entity-web/src/main/java/eu/europeana/entity/web/model/WebConceptSchemeImpl.java
Implemented fixes for serialization of prefLabel and definition fields of ConceptSchema.
> #111 EA-1604 Fix for serialization of ConceptSchema

- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/Organization.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/ResolveController.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/EntityXmlSerializer.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlAddressImpl.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlConstants.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlOrganizationImpl.java
- entity-web/src/main/resources/entity-web-mvc.xml
Branch contains code for organization serialization to rdf/xml and accept header handling
> Ea 1642 organization rdf xml serialization

- entity-web/src/main/java/eu/europeana/entity/web/controller/BaseRest.java
- entity-web/src/main/resources/entity-web-mvc.xml
updated cors headers  and error messages
> #125 implement update entities with groupings

- entity-web/src/main/java/eu/europeana/entity/web/controller/ConceptSchemeController.java
- entity-web/src/main/java/eu/europeana/entity/web/service/authorization/AuthorizationServiceImpl.java
- entity-web/src/main/resources/entity-web-beans.xml
> #143 EA-1764 Implemented bypass API key validation when service is down

- entity-utils/src/main/java/eu/europeana/entity/utils/jsonld/EuropeanaEntityLd.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/ConceptSchemeController.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/SearchController.java
- entity-web/src/main/java/eu/europeana/entity/web/exception/InternalServerException.java
- pom.xml
> #160 EA-1563 changed the total to be a number, response code.

- entity-mongo/src/main/java/eu/europeana/grouping/mongo/model/internal/PersistentConceptScheme.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/SearchController.java
- entity-web/src/main/java/eu/europeana/entity/web/service/impl/EntityServiceImpl.java
sameAs updated by grouping update
> #157 EA-1568 implemented update for sameAs field

- entity-client/pom.xml
- entity-client/src/main/java/eu/europeana/entity/client/connection/EntityApiConnection.java
- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/vocabulary/WebEntityConstants.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/ConceptSchemeController.java
- entity-web/src/main/java/eu/europeana/entity/web/model/vocabulary/Operations.java
Duplicated constants moved to api-commons
> #174 duplicated constants moved to api-commons

- entity-definitions/src/main/java/eu/europeana/entity/web/model/view/EntityPreview.java
- entity-solr/src/main/java/eu/europeana/entity/solr/model/vocabulary/SuggestionFields.java
- entity-solr/src/main/java/eu/europeana/entity/solr/service/impl/SuggestionUtils.java
- entity-solr/src/main/java/eu/europeana/entity/solr/view/EntityPreviewImpl.java
- entity-web/src/main/java/eu/europeana/entity/web/jsonld/SuggestionSetSerializer.java
added isShownBy parameters to suggester response
> #186 EA-2100 implemented isShownBy back to suggester

- entity-client/src/main/java/eu/europeana/entity/client/connection/EntityApiConnection.java
- entity-client/src/main/java/eu/europeana/entity/client/http/HttpConnection.java
- entity-client/src/main/java/eu/europeana/entity/client/web/WebEntityProtocolApi.java
- entity-client/src/main/java/eu/europeana/entity/client/web/WebEntityProtocolApiImpl.java
- entity-client/src/test/java/eu/europeana/entity/client/integration/web/SuggestionSyntaxTest.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/BaseRest.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/SearchController.java
> #188 EA-2096 implemented handling of non word characters on suggester

- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/vocabulary/WebEntityConstants.java
- entity-web/src/main/java/eu/europeana/entity/web/controller/ConceptSchemeController.java
- entity-web/src/main/java/eu/europeana/entity/web/jsonld/SuggestionSetSerializer.java
- entity-web/src/main/java/eu/europeana/entity/web/service/impl/EntityServiceImpl.java
- entity-web/src/main/resources/messages_en.properties
- entity-web/src/main/resources/messages_en.properties.template
> #190 implemented updates for error responses

- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/Timespan.java
- entity-solr/pom.xml
- entity-web/pom.xml
- entity-web/src/main/java/eu/europeana/entity/web/xml/EntityXmlSerializer.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlConstants.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlTimespanImpl.java
- pom.xml
Hi Sergiu,
please review the changes for the ticket EA-2262 about the xml serialization of Timespans.
Many thanks!
Cheers, Srdjan
> #ea 2263 timespans schemaorg

- entity-definitions/src/main/java/eu/europeana/entity/definitions/model/Timespan.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/EntityXmlSerializer.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlAggregationImpl.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlBaseEntityImpl.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlConstants.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlTimespanImpl.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlWebResourceImpl.java
Hi Sergiu,
please have a look at the changes.
Best, Srdjan
> serialized the isShownBy and isNextInSequence fields

- entity-web/src/main/java/eu/europeana/entity/web/xml/EntityXmlSerializer.java
- entity-web/src/main/java/eu/europeana/entity/web/xml/model/XmlBaseEntityImpl.java
Dear Sergiu,
please review the changes. Thank you.
Best, Srdjan
> isShownBy is now serialized for all entities

- pom.xml
preparing for acceptance testing V10
> #EA-2430 updating the version of entity api and corelib to stable
